### ISSUE TITLE
Error in get_explodata 

### ISSUE THREAD

**Issue by Ritzzu** [picardis/nestR#18]
Hi, 

I'm having troubles with the get_explodata function. 

My code looks like that:

   temp_output <- result$nests %>%
        filter(burst == temp_burst)

 (explodata_stork2 <- get_explodata(candidate_nests = temp_output,
                                 known_ids = id_known,
                                 pick_overlapping = FALSE))

The Error message: 
Error in `$<-.data.frame`(`*tmp*`, "nest", value = "no") : 
  replacement has 1 row, data has 0
In addition: Warning message:
In max(rest$tot_vis) : no non-missing arguments to max; returning -Inf
     
Example Data (list) that is stored in the temp_output variable:
![image](https://user-images.githubusercontent.com/30234217/161705804-73073d35-78ed-4ac8-9e0a-2aaccc181b13.png)

id_known variable contains:
burst = "Mirabell   DER AN910 (eobs 3907)"
loc_id = 201434

What am I missing?

**Comment by picardis** [comment]
Hi,

Apologies for the delayed response -- I had notifications off. 

I think the problem is that temp_output only contains one candidate nest location. The candidate_nests argument in get_explodata() needs to be a data frame of several revisited locations obtained in output from find_nests(). If there is only one nest in that data frame, get_explodata() won't be able to find a matching set of nests and non-nests. 

Hope this helps, happy to assist further.
