### ISSUE TITLE
vignette does not build

### ISSUE THREAD

**Issue by andreakoelzsch** [picardis/nestR#22]
Related to the previous issue from Helmut Kruckenberg: I cannot reach the vignette document in any way. Please @picardis could you at least add it here as a pdf? I guess, there all the output columns are described?
THe vignette seems not to be there. When I reinstall nestR locally in RStudio I get the following error:
```
Quitting from lines 710-719 [coda diagnostics] (nestR.Rmd)
   Error: processing vignette 'nestR.Rmd' failed with diagnostics:
   package or namespace load failed for 'rjags':
    .onLoad failed in loadNamespace() for 'rjags', details:
     call: inDL(x, as.logical(local), as.logical(now), ...)
     error: unable to load shared object 'C:/Users/akoelzsch/AppData/Local/R/win-library/4.2/rjags/libs/x64/rjags.dll':
     LoadLibrary failure:  The requested procedure not found.
```
THanks!

**Comment by bsmity13** [comment]
@andreakoelzsch, I would guess that error has to do more with a problem installing `rjags` than with `nestR`, per se. That would be a potential issue not just for the vignette but also for using `nestR` (since `rjags` is listed as an `Import` by `nestR`). There are some specific installation instructions for `rjags` here: https://github.com/cran/rjags/blob/master/INSTALL

**Comment by bsmity13** [comment]
Thanks to a suggestion by @basille, we have knitted a PDF version of the vignette inside the repo at `inst/doc/nestR.pdf`. This should be a more stable resource than the above Google Drive link.

Note that HTML is still the preferred format for readability and navigation.

**Comment by andreakoelzsch** [comment]
@bsmity13 @picardis Thanks you two for the promt replies! The help for rjags and the vignette are highly appreciated. All the best
