### ISSUE TITLE
A visit on the last day of nest cycle drives the reproductive outcome

### ISSUE THREAD

**Issue by janhanz** [picardis/nestR#28]
We are calculating nesting success for a nesting attempt using `phi_time_p_time` model in a function `estimate_outcomes`. In an extreme (simulated) case when a nest was visited just on the first day and the last day of the `nest_cycle`, such nesting attempt is evaluated as successful. However, we would also like to take into account the days without any visits to the nests. Based on the knowledge of breeding biology of our study species, we assume that just a single day without nest visits means failure.

How should we modify the nest survival model to detect failure in such cases?

I made some experiments with modifying the function `initialize_z`, to assign `NA` to days in the nesting cycle, starting with the first day with 0 visits. But the JAGS model is not converging, throwing `Node inconsistent with parents` error (likely because days with non-zero visits exist after the first day with 0 visits?).

Any help is welcome : ).

**Comment by bsmity13** [comment]
Thanks for the message. You are correct that a visit on the last day would drive the reproductive outcome. That is because the model necessarily assumes that any visits to the nest are to care for live young. That is, the likelihood of _observing_ a visit on a given day is $p$ if the nest is alive (i.e., $z_t = 1$), and 0 if the nest has failed (i.e., $z_t = 0$). Success is defined as the nest being alive on the last day (time $t = T$), i.e., $z_{t=T} = 1$. So an observation can only occur if the nest is alive. Thus, if a nest visit is observed on the last day, the nest is assumed to succeed with probability 1. Only "capture histories" ending in 0 have probability of success < 1. This is the observation part of the model (it describes how the response variable arises from the latent state process).

The state process of the model is tracked by the _latent_ state variable $z_t$, which is modeled like traditional survival in a mark-recapture model. If at any point $z_t = 0$, then all $z$ after that time must be 0 (a nest cannot come back to life). So if $z_{t=T} = 1$, all other $z_t$ must also be 1. 

 In theory, it would be possible to formulate a model that allows for visits to the nest despite nest failure (i.e., $y_t = 1, z_t = 0$), but I think that would require a separate source of information (i.e., an independent data source) to estimate the probability of visiting an already failed nest.

Sorry if that isn't helpful, but it sounds like you may need some new model development to accomodate the biology of your system.

**Comment by janhanz** [comment]
Thank you for a thorough explanation. Yes, it seems we likely need a different nest survival model than the one that is currently implemented in nestR. We will have a look at the implementation, if it is not too complicated.
